# This file is part of the ylebich.js.
#
# (c) 2021 Temuri Takalandze <me@abgeo.dev>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

name: Publish Package

on:
  release:
    types: [ published ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
